#!/usr/bin/env bash
#
# generate_build_info.sh
#
# Generates src/shared/_build_info.py with build metadata.
# This file is gitignored and only exists inside the Docker images.
#
# Purpose:
#   - Know exactly which commit, tag, branch and build time is running in production.
#   - Useful for /version endpoints, admin dashboard, logs, and incident investigation.
#   - .git directory is not available inside containers.
#
# Run manually or automatically from deploy scripts / Makefile before `docker build`.
#
set -euo pipefail

cd "$(dirname "$0")/.."

# --- Collect data ---

if git rev-parse --git-dir > /dev/null 2>&1; then
    COMMIT=$(git rev-parse HEAD)
    COMMIT_SHORT=$(git rev-parse --short HEAD)
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
else
    echo ">>> WARNING: Not inside a git repository. Using fallback values."
    COMMIT="unknown"
    COMMIT_SHORT="dev"
    BRANCH="unknown"
    TAG=""
fi

BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Get version from pyproject.toml using only stdlib
if command -v python3 >/dev/null 2>&1; then
    APP_VERSION=$(python3 -c '
import tomllib
from pathlib import Path
pyproject = Path("pyproject.toml")
if pyproject.exists():
    data = tomllib.loads(pyproject.read_text())
    print(data.get("project", {}).get("version", "0.0.0"))
else:
    print("0.0.0")
' 2>/dev/null || echo "0.0.0")
else
    APP_VERSION="0.0.0"
fi

# --- Write the file ---

OUTPUT_FILE="src/shared/_build_info.py"

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
"""Auto-generated build metadata.

DO NOT EDIT MANUALLY.
This file is generated by scripts/generate_build_info.sh before every Docker build.
It is gitignored and exists only inside the built container images.

Generated at: ${BUILD_TIME}
"""

from __future__ import annotations

APP_VERSION: str = "${APP_VERSION}"
GIT_COMMIT: str = "${COMMIT}"
GIT_COMMIT_SHORT: str = "${COMMIT_SHORT}"
GIT_BRANCH: str = "${BRANCH}"
GIT_TAG: str = "${TAG}"
BUILD_TIME: str = "${BUILD_TIME}"
EOF

echo "✓ Generated ${OUTPUT_FILE}"
echo ""
cat "$OUTPUT_FILE"
echo ""